---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maya-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: maya-frontend
  template:
    metadata:
      labels:
        component: maya-frontend
    spec:
      containers:
        - name: maya-frontend
          image: maya-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: maya-front-service   # Name of the resource
spec:
  type: NodePort                 # If you're deploying on cloud, you can use `type: LoadBalancer`. It will automatically provision a load balancer with the cloud provider that will route traffic to your application.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9091
    targetPort: 80
  selector:
    app: maya-frontend          # Map any pod with name maya-app to this service